// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DataPicker: typeof import('./src/components/data-picker/index.vue')['default']
    DelWrap: typeof import('./src/components/del-wrap/index.vue')['default']
    DictValue: typeof import('./src/components/dict-value/index.vue')['default']
    Editor: typeof import('./src/components/editor/index.vue')['default']
    FileItem: typeof import('./src/components/material-select/file-item.vue')['default']
    FooterBtns: typeof import('./src/components/footer-btns/index.vue')['default']
    Material: typeof import('./src/components/material-select/material.vue')['default']
    MaterialSelect: typeof import('./src/components/material-select/index.vue')['default']
    Pagination: typeof import('./src/components/pagination/index.vue')['default']
    PopoverInput: typeof import('./src/components/popover-input/index.vue')['default']
    Popup: typeof import('./src/components/popup/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Upload: typeof import('./src/components/upload/index.vue')['default']
  }
}

export {}
